version: '3.8'

services:
  app:
    container_name: codeigniter-app
    build: .
    ports:
      - "8080:8080"
    volumes:
      - "./app:/app"
    depends_on:
      - db
    environment:
      - CI_ENVIRONMENT=development
      - database.default.hostname=db
      - database.default.database=ci4tutorial
      - database.default.username=root
      - database.default.password=root
      - database.default.DBDriver=MySQLi


  db:
    container_name: codeigniter-mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ci4tutorial
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: